// lib/staticData.js
// İlk kurulumda ya da API yokken gösterilecek örnek veriler

export const STATIC_NEWS = {
  general: [
    {
      title: "PSG, Arsenal'ı Penaltılarda Yıktı — Art Arda İkinci Şampiyonluk!",
      summary: "Budapeşte'de oynanan final 1-1 bitti, penaltılarda PSG 4-3 galip geldi. Eze ve Gabriel penaltı kaçırdı. PSG, 2014-17 Real Madrid'den bu yana art arda şampiyon olan ilk takım oldu.",
      source: "UEFA",
      flag: "🏆",
      date: new Date().toISOString(),
      link: "https://www.uefa.com",
      image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80",
    },
    {
      title: "La Liga Son Haftası: Valencia 3-1 Barcelona — Barça Şampiyonluğu Kaçırdı",
      summary: "Sezon finalinde büyük sürpriz yaşandı. Barcelona, Valencia deplasmanında 3-1 mağlup oldu ve La Liga şampiyonluğunu kaçırdı.",
      source: "Marca",
      flag: "🇪🇸",
      date: new Date().toISOString(),
      link: "https://www.marca.com",
      image: "https://images.unsplash.com/photo-1522778526097-ce0a22ceb253?w=800&q=80",
    },
    {
      title: "Real Madrid Sezonu Zaferle Kapattı: 4-2 Athletic Bilbao",
      summary: "Madrid son maçta 4 golle coştu. Vinicius Jr. 2 gol attı, Bellingham asist yaptı.",
      source: "Marca",
      flag: "🇪🇸",
      date: new Date().toISOString(),
      link: "https://www.marca.com",
      image: "https://images.unsplash.com/photo-1459865264687-595d652de67e?w=800&q=80",
    },
    {
      title: "Manchester United Brighton'ı 3-0 Geçti, Sezon Galibiyetle Bitti",
      summary: "United sezon finalinde Brighton'da 3-0'lık güçlü bir galibiyet aldı. Rasmus Hojlund 2 gol attı.",
      source: "BBC Sport",
      flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
      date: new Date().toISOString(),
      link: "https://www.bbc.com/sport/football",
      image: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&q=80",
    },
    {
      title: "Premier League'de Sürpriz Kapanış: Sunderland, Chelsea'yi 2-1 Yendi",
      summary: "Chelsea beklenmedik bir yenilgi aldı. Sunderland yeni çıktığı Premier League'de sezonu galibiyetle kapattı.",
      source: "Sky Sports",
      flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
      date: new Date().toISOString(),
      link: "https://www.skysports.com",
      image: "https://images.unsplash.com/photo-1516731415730-0c607149933a?w=800&q=80",
    },
    {
      title: "Villarreal 5-1 Atletico Madrid — Sezonu Büyük Farkla Kapattı",
      summary: "Villarreal inanılmaz bir performans sergileyerek Atletico'yu yerle bir etti. Muşik Torres hat-trick yaptı.",
      source: "Marca",
      flag: "🇪🇸",
      date: new Date().toISOString(),
      link: "https://www.marca.com",
      image: "https://images.unsplash.com/photo-1518604666860-9ed391f76460?w=800&q=80",
    },
  ],
  transfer: [
    {
      title: "Liverpool'da Slot Dönemi Bitiyor — Iraola 1/20 Favori!",
      summary: "Liverpool yönetimi Bournemouth'un başarılı hocası Andoni Iraola ile görüşmelere başladı. Bahis şirketleri Iraola'yı ezici favori gösteriyor.",
      source: "Sky Sports",
      flag: "🔴",
      date: new Date().toISOString(),
      link: "https://www.skysports.com",
      image: "https://images.unsplash.com/photo-1599394022918-6c2776530abb?w=800&q=80",
    },
    {
      title: "Yaz Transfer Penceresi 15 Haziran'da Açılıyor",
      summary: "Premier League yaz transfer dönemi 15 Haziran'da başlayacak, 1 Eylül gece yarısı kapanacak. Dünya Kupası nedeniyle pencere erken kapanabilir.",
      source: "Sky Sports",
      flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
      date: new Date().toISOString(),
      link: "https://www.skysports.com",
      image: "https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=800&q=80",
    },
    {
      title: "Arteta: 'Bu Yaz Çok Hırslı Olacağız'",
      summary: "Şampiyonlar Ligi finalinde kaybeden Arsenal'ın teknik direktörü Arteta, yaz transfer döneminde büyük isimler getireceğinin sinyalini verdi.",
      source: "BBC Sport",
      flag: "🔴",
      date: new Date().toISOString(),
      link: "https://www.bbc.com/sport",
      image: "https://images.unsplash.com/photo-1551958219-acbc595e4d74?w=800&q=80",
    },
  ],
  magazine: [
    {
      title: "Gabriel'in Kaçırdığı Penaltı Sosyal Medyayı Salladı — Chelsea'den Acımasız Gönderme!",
      summary: "Finalin en dramatik anında Gabriel direkten üst topun üstünden gönderdi. Dakikalar sonra Chelsea resmi hesabından 'Londra'nın Kupa Evi'ne bekleriz' paylaşımı geldi.",
      source: "CNN",
      flag: "💥",
      date: new Date().toISOString(),
      link: "https://www.cnn.com",
      image: "https://images.unsplash.com/photo-1551958219-acbc595e4d74?w=800&q=80",
    },
    {
      title: "Havertz, 2 Farklı Takımla Şampiyonlar Ligi Finalinde Gol Atan 3. Oyuncu Oldu",
      summary: "Chelsea formasıyla 2021, Arsenal formasıyla 2026 — Havertz futbol tarihine geçti.",
      source: "UEFA",
      flag: "⭐",
      date: new Date().toISOString(),
      link: "https://www.uefa.com",
      image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&q=80",
    },
  ],
  worldcup: [],
};

export const STATIC_MATCHES = [
  { home: "Paris Saint-Germain", away: "Arsenal", date: "2026-05-30", status: "FINISHED", score: "1-1 (pen 4-3)", leagueName: "Şampiyonlar Ligi", leagueFlag: "🏆" },
  { home: "Valencia CF", away: "FC Barcelona", date: "2026-05-23", status: "FINISHED", score: "3-1", leagueName: "La Liga", leagueFlag: "🇪🇸" },
  { home: "Real Madrid", away: "Athletic Bilbao", date: "2026-05-23", status: "FINISHED", score: "4-2", leagueName: "La Liga", leagueFlag: "🇪🇸" },
  { home: "Villarreal CF", away: "Atletico Madrid", date: "2026-05-24", status: "FINISHED", score: "5-1", leagueName: "La Liga", leagueFlag: "🇪🇸" },
  { home: "Brighton", away: "Man United", date: "2026-05-24", status: "FINISHED", score: "0-3", leagueName: "Premier League", leagueFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { home: "Sunderland", away: "Chelsea", date: "2026-05-24", status: "FINISHED", score: "2-1", leagueName: "Premier League", leagueFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { home: "Man City", away: "Aston Villa", date: "2026-05-24", status: "FINISHED", score: "1-2", leagueName: "Premier League", leagueFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { home: "Liverpool", away: "Brentford", date: "2026-05-24", status: "FINISHED", score: "1-1", leagueName: "Premier League", leagueFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { home: "Tottenham", away: "Everton", date: "2026-05-24", status: "FINISHED", score: "1-0", leagueName: "Premier League", leagueFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { home: "West Ham", away: "Leeds United", date: "2026-05-24", status: "FINISHED", score: "3-0", leagueName: "Premier League", leagueFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
];
